"""mcp server proposals

Revision ID: b733fb162c82
Revises: c7f41ab9e3d2
Create Date: 2026-07-30 18:25:49.070794

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = 'b733fb162c82'
down_revision = 'c7f41ab9e3d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_server_proposal',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('proposed_by', sa.GUID(length=16), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('tool_allowlist', sa.JSON(), nullable=False),
    sa.Column('encrypted_auth', sa.String(), nullable=True),
    sa.Column('auth_key_id', sa.GUID(length=16), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('server_id', sa.GUID(length=16), nullable=True),
    sa.Column('decided_by', sa.GUID(length=16), nullable=True),
    sa.Column('decided_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auth_key_id'], ['secret_key.id'], name=op.f('fk_mcp_server_proposal_auth_key_id_secret_key')),
    sa.ForeignKeyConstraint(['decided_by'], ['user_account.id'], name=op.f('fk_mcp_server_proposal_decided_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by'], ['user_account.id'], name=op.f('fk_mcp_server_proposal_proposed_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_server.id'], name=op.f('fk_mcp_server_proposal_server_id_mcp_server'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_mcp_server_proposal_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_server_proposal'))
    )
    with op.batch_alter_table('mcp_server_proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_proposal_proposed_by'), ['proposed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_proposal_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_proposal_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_server_proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_proposal_team_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_proposal_status'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_proposal_proposed_by'))

    op.drop_table('mcp_server_proposal')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
