"""mcp tool server registry

Revision ID: d2b956dbc5ae
Revises: a1975b24b2d2
Create Date: 2026-07-30 14:51:17.624677

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = 'd2b956dbc5ae'
down_revision = 'a1975b24b2d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_server',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('tool_allowlist', sa.JSON(), nullable=False),
    sa.Column('encrypted_auth', sa.String(), nullable=True),
    sa.Column('auth_key_id', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['auth_key_id'], ['secret_key.id'], name=op.f('fk_mcp_server_auth_key_id_secret_key')),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_mcp_server_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_server')),
    sa.UniqueConstraint('team_id', 'name', name=op.f('uq_mcp_server_team_id'))
    )
    with op.batch_alter_table('mcp_server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_team_id'), ['team_id'], unique=False)

    op.create_table('mcp_server_grant',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('server_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_server.id'], name=op.f('fk_mcp_server_grant_server_id_mcp_server'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_mcp_server_grant_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_server_grant')),
    sa.UniqueConstraint('server_id', 'team_id', name=op.f('uq_mcp_server_grant_server_id'))
    )
    with op.batch_alter_table('mcp_server_grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_grant_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_grant_team_id'), ['team_id'], unique=False)

    op.create_table('mcp_server_suppression',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('server_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_server.id'], name=op.f('fk_mcp_server_suppression_server_id_mcp_server'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_mcp_server_suppression_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_server_suppression')),
    sa.UniqueConstraint('server_id', 'team_id', name=op.f('uq_mcp_server_suppression_server_id'))
    )
    with op.batch_alter_table('mcp_server_suppression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_server_suppression_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_server_suppression_team_id'), ['team_id'], unique=False)

    op.create_table('mcp_tool',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('server_id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('effect', sa.String(), nullable=False),
    sa.Column('discovered_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_server.id'], name=op.f('fk_mcp_tool_server_id_mcp_server'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_tool')),
    sa.UniqueConstraint('server_id', 'name', name=op.f('uq_mcp_tool_server_id'))
    )
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tool_server_id'), ['server_id'], unique=False)

    op.create_table('api_key_tool_policy',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('api_key_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('destructive_enabled', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], name=op.f('fk_api_key_tool_policy_api_key_id_api_key'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_api_key_tool_policy_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_key_tool_policy'))
    )
    with op.batch_alter_table('api_key_tool_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_tool_policy_api_key_id'), ['api_key_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_key_tool_policy_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key_tool_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_tool_policy_team_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_tool_policy_api_key_id'))

    op.drop_table('api_key_tool_policy')
    with op.batch_alter_table('mcp_tool', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tool_server_id'))

    op.drop_table('mcp_tool')
    with op.batch_alter_table('mcp_server_suppression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_suppression_team_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_suppression_server_id'))

    op.drop_table('mcp_server_suppression')
    with op.batch_alter_table('mcp_server_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_grant_team_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_server_grant_server_id'))

    op.drop_table('mcp_server_grant')
    with op.batch_alter_table('mcp_server', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_server_team_id'))

    op.drop_table('mcp_server')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
