"""add budget alert state and budget thresholds

Revision ID: 5e4c132e7869
Revises: f358c2474285
Create Date: 2026-07-27 01:11:23.840028

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    Bool,
    EncryptedString,
    EncryptedText,
    GUID,
    JsonB,
    ORA_JSONB,
    DateTimeUTC,
    StoredObject,
    PasswordHash,
    FernetBackend,
    TOTPSecret,
    OneTimeCode,
)
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = (
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
)

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = "5e4c132e7869"
down_revision = "f358c2474285"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget_alert_state",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("team_id", sa.GUID(length=16), nullable=False),
        sa.Column("window", sa.String(), nullable=False),
        sa.Column("period_start", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("threshold", sa.Integer(), nullable=False),
        sa.Column("fired_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"], ["team.id"], name=op.f("fk_budget_alert_state_team_id_team")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_alert_state")),
        sa.UniqueConstraint(
            "team_id",
            "window",
            "period_start",
            "threshold",
            name=op.f("uq_budget_alert_state_team_id"),
        ),
    )
    with op.batch_alter_table("budget_alert_state", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_budget_alert_state_team_id"), ["team_id"], unique=False
        )

    with op.batch_alter_table("team_budget", schema=None) as batch_op:
        # server_default '[]' backfills existing rows so the NOT NULL add
        # succeeds on a populated table; new inserts get their value from the
        # ORM default.
        batch_op.add_column(
            sa.Column("thresholds", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("team_budget", schema=None) as batch_op:
        batch_op.drop_column("thresholds")

    with op.batch_alter_table("budget_alert_state", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budget_alert_state_team_id"))

    op.drop_table("budget_alert_state")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
