"""nullable router.team_id + router_grant + origin

Revision ID: c6366c44d858
Revises: b213468f39d2
Create Date: 2026-07-22 11:45:56.056968

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    Bool,
    EncryptedString,
    EncryptedText,
    GUID,
    JsonB,
    ORA_JSONB,
    DateTimeUTC,
    StoredObject,
    PasswordHash,
    FernetBackend,
    TOTPSecret,
    OneTimeCode,
)
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = (
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
)

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = "c6366c44d858"
down_revision = "b213468f39d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # Self-healing (see the model_grant migration): tolerate a router_grant /
    # index already built by a prior create_all so `database upgrade` succeeds.
    inspector = sa.inspect(op.get_bind())
    tables = set(inspector.get_table_names())

    if "router_grant" not in tables:
        op.create_table(
            "router_grant",
            sa.Column("id", sa.GUID(length=16), nullable=False),
            sa.Column("router_id", sa.GUID(length=16), nullable=False),
            sa.Column("team_id", sa.GUID(length=16), nullable=False),
            sa.Column("alias", sa.String(), nullable=False),
            sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
            sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(
                ["router_id"],
                ["router.id"],
                name=op.f("fk_router_grant_router_id_router"),
                ondelete="CASCADE",
            ),
            sa.ForeignKeyConstraint(
                ["team_id"], ["team.id"], name=op.f("fk_router_grant_team_id_team")
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_router_grant")),
            sa.UniqueConstraint("router_id", "team_id", name=op.f("uq_router_grant_router_id")),
            sa.UniqueConstraint("team_id", "alias", name=op.f("uq_router_grant_team_id")),
        )
        with op.batch_alter_table("router_grant", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_router_grant_router_id"), ["router_id"], unique=False
            )
            batch_op.create_index(batch_op.f("ix_router_grant_team_id"), ["team_id"], unique=False)

    router_columns = {c["name"] for c in inspector.get_columns("router")}
    router_indexes = {ix["name"] for ix in inspector.get_indexes("router")}
    with op.batch_alter_table("router", schema=None) as batch_op:
        if "origin_team_id" not in router_columns:
            batch_op.add_column(sa.Column("origin_team_id", sa.GUID(length=16), nullable=True))
        batch_op.alter_column("team_id", nullable=True)
        if "uq_global_router_name" not in router_indexes:
            batch_op.create_index(
                "uq_global_router_name",
                ["name"],
                unique=True,
                sqlite_where=sa.text("team_id IS NULL"),
                postgresql_where=sa.text("team_id IS NULL"),
            )


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("router", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_global_router_name",
            sqlite_where=sa.text("team_id IS NULL"),
            postgresql_where=sa.text("team_id IS NULL"),
        )
        batch_op.alter_column("team_id", nullable=False)
        batch_op.drop_column("origin_team_id")

    with op.batch_alter_table("router_grant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_router_grant_team_id"))
        batch_op.drop_index(batch_op.f("ix_router_grant_router_id"))

    op.drop_table("router_grant")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Seed provenance: a team-owned router's origin is its own team."""
    op.execute(
        "UPDATE router SET origin_team_id = team_id "
        "WHERE origin_team_id IS NULL AND team_id IS NOT NULL"
    )


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
