"""add model.origin_team_id

Revision ID: b213468f39d2
Revises: 90e784ecd46b
Create Date: 2026-07-22 01:29:37.385778

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    Bool,
    EncryptedString,
    EncryptedText,
    GUID,
    JsonB,
    ORA_JSONB,
    DateTimeUTC,
    StoredObject,
    PasswordHash,
    FernetBackend,
    TOTPSecret,
    OneTimeCode,
)
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = (
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
)

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = "b213468f39d2"
down_revision = "90e784ecd46b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model", schema=None) as batch_op:
        batch_op.add_column(sa.Column("origin_team_id", sa.GUID(length=16), nullable=True))

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model", schema=None) as batch_op:
        batch_op.drop_column("origin_team_id")

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Seed provenance for existing rows: a team-owned model's origin is its own
    team. Existing globals (team_id IS NULL) keep origin NULL. Portable across
    SQLite and Postgres."""
    op.execute(
        "UPDATE model SET origin_team_id = team_id "
        "WHERE origin_team_id IS NULL AND team_id IS NOT NULL"
    )


def data_downgrades() -> None:
    """Restore promoted models to their origin before dropping provenance."""
    bind = op.get_bind()
    native = list(
        bind.execute(
            sa.text(
                "SELECT name FROM model "
                "WHERE team_id IS NULL AND origin_team_id IS NULL "
                "ORDER BY name LIMIT 5"
            )
        ).scalars()
    )
    missing_origins = list(
        bind.execute(
            sa.text(
                "SELECT model.name FROM model "
                "LEFT JOIN team ON team.id = model.origin_team_id "
                "WHERE model.team_id IS NULL AND model.origin_team_id IS NOT NULL "
                "AND team.id IS NULL ORDER BY model.name LIMIT 5"
            )
        ).scalars()
    )
    collisions = list(
        bind.execute(
            sa.text(
                "SELECT global_model.name FROM model AS global_model "
                "JOIN model AS local_model "
                "ON local_model.team_id = global_model.origin_team_id "
                "AND local_model.name = global_model.name "
                "AND local_model.id <> global_model.id "
                "WHERE global_model.team_id IS NULL "
                "ORDER BY global_model.name LIMIT 5"
            )
        ).scalars()
    )
    blockers: list[str] = []
    if native:
        blockers.append(f"native global model without origin_team_id: {native!r}")
    if missing_origins:
        blockers.append(f"model origin_team_id does not reference an existing team: {missing_origins!r}")
    if collisions:
        blockers.append(f"model name already exists in its origin team: {collisions!r}")
    if blockers:
        raise RuntimeError(
            "Cannot downgrade global models safely: "
            + "; ".join(blockers)
            + ". Reassign or intentionally delete each blocked resource, then retry. "
            "See docs/db-migrations.md#downgrading-global-resources. "
            "No schema DDL from revision b213468f39d2 was applied."
        )

    bind.execute(
        sa.text(
            "UPDATE model SET team_id = origin_team_id "
            "WHERE team_id IS NULL AND origin_team_id IS NOT NULL"
        )
    )
