"""nullable model.team_id + model_grant table

Revision ID: 90e784ecd46b
Revises: 79fc50bbd1a4
Create Date: 2026-07-22 00:42:09.467102

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '90e784ecd46b'
down_revision = '79fc50bbd1a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_grant',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('model_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_model_grant_model_id_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_model_grant_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_grant')),
    sa.UniqueConstraint('model_id', 'team_id', name=op.f('uq_model_grant_model_id')),
    sa.UniqueConstraint('team_id', 'alias', name=op.f('uq_model_grant_team_id'))
    )
    with op.batch_alter_table('model_grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_grant_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_grant_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.alter_column('team_id',
               nullable=True)
        batch_op.create_index('uq_global_model_name', ['name'], unique=True, sqlite_where=sa.text('team_id IS NULL'), postgresql_where=sa.text('team_id IS NULL'))

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_index('uq_global_model_name', sqlite_where=sa.text('team_id IS NULL'), postgresql_where=sa.text('team_id IS NULL'))
        batch_op.alter_column('team_id',
               nullable=False)

    with op.batch_alter_table('model_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_grant_team_id'))
        batch_op.drop_index(batch_op.f('ix_model_grant_model_id'))

    op.drop_table('model_grant')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
