"""per-team alert webhook signing secret

An optional per-team HMAC secret for the team's own budget-alert webhook,
envelope-encrypted like every other stored secret. NULL means "sign with the
platform-wide secret", which is what every existing row means — so this is
additive and changes no behaviour until a team sets one.

Revision ID: 1ba3abd4b3e2
Revises: 5baa739f5c59
Create Date: 2026-07-29 12:34:29.476333

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '1ba3abd4b3e2'
down_revision = '5baa739f5c59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_alert_webhook_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('alert_webhook_secret_key_id', sa.GUID(length=16), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_team_budget_alert_webhook_secret_key_id_secret_key'), 'secret_key', ['alert_webhook_secret_key_id'], ['id'])

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_budget', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_team_budget_alert_webhook_secret_key_id_secret_key'), type_='foreignkey')
        batch_op.drop_column('alert_webhook_secret_key_id')
        batch_op.drop_column('encrypted_alert_webhook_secret')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
