"""allow session-authenticated usage without a synthetic API key

Revision ID: d41e8f6a2c10
Revises: c6366c44d858
Create Date: 2026-07-22 16:00:00.000000

"""

from __future__ import annotations

import warnings

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import GUID

revision = "d41e8f6a2c10"
down_revision = "c6366c44d858"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_downgrades()


def schema_upgrades() -> None:
    """Allow usage generated by a human session to omit an API-key identity."""
    with op.batch_alter_table("usage_event", schema=None) as batch_op:
        batch_op.alter_column("api_key_id", existing_type=GUID(), nullable=True)
    with op.batch_alter_table("pending_usage_event", schema=None) as batch_op:
        batch_op.alter_column("api_key_id", existing_type=GUID(), nullable=True)


def schema_downgrades() -> None:
    """Restore the original API-key-only ledger contract on compatible data."""
    connection = op.get_bind()
    session_rows = connection.scalar(
        sa.text(
            "SELECT (SELECT COUNT(*) FROM usage_event WHERE api_key_id IS NULL) + "
            "(SELECT COUNT(*) FROM pending_usage_event WHERE api_key_id IS NULL)"
        )
    )
    if session_rows:
        raise RuntimeError(
            "cannot downgrade while session-authenticated usage rows exist; "
            "export or remove those rows explicitly before retrying"
        )
    with op.batch_alter_table("pending_usage_event", schema=None) as batch_op:
        batch_op.alter_column("api_key_id", existing_type=GUID(), nullable=False)
    with op.batch_alter_table("usage_event", schema=None) as batch_op:
        batch_op.alter_column("api_key_id", existing_type=GUID(), nullable=False)


def data_upgrades() -> None:
    """No data migration is required."""


def data_downgrades() -> None:
    """No data migration is required."""
