"""add routing_decision router_id

Revision ID: 83c6a8d7ba98
Revises: 9f29c0689319
Create Date: 2026-07-21 01:14:12.017122

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '83c6a8d7ba98'
down_revision = '9f29c0689319'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routing_decision', schema=None) as batch_op:
        batch_op.add_column(sa.Column('router_id', sa.GUID(length=16), nullable=True))
        batch_op.create_index('ix_routing_decision_team_id_router_id_created_at', ['team_id', 'router_id', 'created_at'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routing_decision', schema=None) as batch_op:
        batch_op.drop_index('ix_routing_decision_team_id_router_id_created_at')
        batch_op.drop_column('router_id')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Backfill router_id for decisions whose router still exists.

    Router name is unique among *existing* routers, so the (team_id, name) join
    is unambiguous for live routers — those rows get their id. Decisions of
    already-deleted routers keep router_id NULL: their history intentionally
    stays out of any future router that reuses the name. Portable correlated
    UPDATE (SQLite + Postgres)."""
    op.execute(
        """
        UPDATE routing_decision
        SET router_id = (
            SELECT router.id FROM router
            WHERE router.team_id = routing_decision.team_id
              AND router.name = routing_decision.router_name
        )
        WHERE router_id IS NULL
          AND EXISTS (
            SELECT 1 FROM router
            WHERE router.team_id = routing_decision.team_id
              AND router.name = routing_decision.router_name
          )
        """
    )

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
