"""guardrail rule table

Plan 06 / Plan 17 Slice 6c. One row per configured guardrail provider in a
team's chain. Additive: a deployment with no rows behaves exactly as before,
since an empty chain is indistinguishable from no guardrails at all.

`encrypted_secret` holds the webhook signing secret under the same envelope
scheme as provider credentials (`key_id` → `secret_key`), so a downgrade drops
the ciphertext with the table and never leaves it decryptable elsewhere.

Revision ID: 5363a209ffc8
Revises: 97f0f6ad000d
Create Date: 2026-07-29 11:05:37.494345

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '5363a209ffc8'
down_revision = '97f0f6ad000d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrail_rule',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    sa.Column('model_id', sa.GUID(length=16), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('fail_policy', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('encrypted_secret', sa.String(), nullable=True),
    sa.Column('key_id', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['secret_key.id'], name=op.f('fk_guardrail_rule_key_id_secret_key')),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], name=op.f('fk_guardrail_rule_model_id_model'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_guardrail_rule_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guardrail_rule')),
    sa.UniqueConstraint('team_id', 'name', name=op.f('uq_guardrail_rule_team_id'))
    )
    with op.batch_alter_table('guardrail_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardrail_rule_model_id'), ['model_id'], unique=False)
        batch_op.create_index('ix_guardrail_rule_team_direction', ['team_id', 'direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardrail_rule_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guardrail_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardrail_rule_team_id'))
        batch_op.drop_index('ix_guardrail_rule_team_direction')
        batch_op.drop_index(batch_op.f('ix_guardrail_rule_model_id'))

    op.drop_table('guardrail_rule')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
