"""api key budget table

Plan 13 Phase 4 / Plan 17 Slice 7. One optional spend cap per API key, always a
sub-limit of the team's cap: the team gate runs regardless, so this table can
only ever make a key spend less, never more.

Additive — no rows means no per-key caps, and admission behaves exactly as
before. `api_key_id` is ON DELETE CASCADE: a cap for a deleted key would be a
row nothing can reach, and the key's usage history is kept separately.

Revision ID: 5baa739f5c59
Revises: 5363a209ffc8
Create Date: 2026-07-29 11:54:41.344811

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = '5baa739f5c59'
down_revision = '5363a209ffc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_budget',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('api_key_id', sa.GUID(length=16), nullable=False),
    sa.Column('team_id', sa.GUID(length=16), nullable=False),
    # The `Money` TypeDecorator's underlying type, spelled out: a migration
    # must not depend on an application type being importable here.
    sa.Column('limit_cost', sa.Numeric(20, 6), nullable=False),
    sa.Column('window', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], name=op.f('fk_api_key_budget_api_key_id_api_key'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_api_key_budget_team_id_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_key_budget'))
    )
    with op.batch_alter_table('api_key_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_budget_api_key_id'), ['api_key_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_key_budget_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_key_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_budget_team_id'))
        batch_op.drop_index(batch_op.f('ix_api_key_budget_api_key_id'))

    op.drop_table('api_key_budget')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
