"""add secret_key keyring + credential key_id

Revision ID: f7df7d9dca05
Revises: 3bde5e9b6c0a
Create Date: 2026-07-01 13:59:46.618247

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import Bool, EncryptedString, EncryptedText, GUID, JsonB, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend, TOTPSecret, OneTimeCode
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401


if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ("downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades")

sa.GUID = GUID
sa.Bool = Bool
sa.DateTimeUTC = DateTimeUTC
sa.JsonB = JsonB
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend
sa.TOTPSecret = TOTPSecret
sa.OneTimeCode = OneTimeCode

# revision identifiers, used by Alembic.
revision = 'f7df7d9dca05'
down_revision = '3bde5e9b6c0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_key',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.Column('retired_at', sa.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_key'))
    )
    with op.batch_alter_table('secret_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_key_purpose'), ['purpose'], unique=False)

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_id', sa.GUID(length=16), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_credential_key_id_secret_key'), 'secret_key', ['key_id'], ['id'])

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_credential_key_id_secret_key'), type_='foreignkey')
        batch_op.drop_column('key_id')

    with op.batch_alter_table('secret_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_key_purpose'))

    op.drop_table('secret_key')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
