"""Port — the in-flight spend a team has admitted but not yet settled.

The ledger SUM in PostgreSQL is authoritative for what a team *has* spent; this
port bounds what it is *about to* spend. Every admitted request reserves its
pessimistic cost until settlement releases it, so a burst of concurrent calls —
streams especially, which settle minutes after admission — cannot all slip under
a nearly-exhausted cap.

Reservations are keyed by a server-generated id and expire after a bounded TTL,
which is what makes the protocol recoverable: a replica that dies mid-request
takes its in-memory state with it, and without expiry its reservations would
hold a team's headroom hostage forever.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, runtime_checkable
from uuid import UUID


@dataclass(frozen=True)
class Reservation:
    """One admitted-but-unsettled request's claim on a team's budget.

    `id` is generated by the store, never by a client, and is the whole identity
    of the claim: releasing is deleting that id, which makes a double release a
    no-op instead of silently under-counting the way subtracting a float twice
    would.
    """

    id: UUID
    team_id: UUID
    amount: float


@dataclass(frozen=True)
class ReservationOutcome:
    """The verdict of one admission attempt.

    `reserved` is the in-flight total the decision actually saw, carried out so
    the caller can put a real number in the refusal message instead of reading
    it back in a second, racy round trip.
    """

    reservation: Reservation | None
    reserved: float

    @property
    def admitted(self) -> bool:
        return self.reservation is not None


@runtime_checkable
class BudgetReservationStore(Protocol):
    """Shared in-flight spend, atomic per team.

    `try_reserve` must read the current in-flight total, decide, and record the
    new reservation as ONE indivisible step. Splitting it lets two concurrent
    admissions both read the same total and both slip under the cap — the exact
    property the single-process implementation got for free by not awaiting
    between the read and the write, and the reason a distributed version needs a
    server-side script rather than a read followed by a write.

    `spent` and `limit` are passed in because settlement stays authoritative in
    PostgreSQL: the store bounds concurrency, it does not own the budget.
    """

    async def try_reserve(
        self,
        team_id: UUID,
        amount: float,
        *,
        spent: float,
        limit: float,
        ttl_s: int,
    ) -> ReservationOutcome: ...

    async def release(self, reservation: Reservation) -> None:
        """Give back a reservation. Idempotent: releasing twice, or releasing
        one the store already expired, must be a no-op."""
        ...
